-- Seed masivo local de body_type (sin Mercado Libre)
-- Generado desde public/brands-data.json

BEGIN;

INSERT INTO public.vehicle_body_type_cache
(brand, model, normalized_brand, normalized_model, body_type, confidence, sample_size, source, source_item_id, created_at, updated_at)
VALUES
('Acura','ILX','acura','ilx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Acura','MDX','acura','mdx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Acura','RDX','acura','rdx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Acura','TL','acura','tl','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Acura','TLX','acura','tlx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','147','alfa romeo','147','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','156','alfa romeo','156','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','159','alfa romeo','159','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','166','alfa romeo','166','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','Giulia','alfa romeo','giulia','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','Giulietta','alfa romeo','giulietta','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','MiTo','alfa romeo','mito','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','Stelvio','alfa romeo','stelvio','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Alfa Romeo','Tonale','alfa romeo','tonale','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Aston Martin','DB11','aston martin','db11','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Aston Martin','DB9','aston martin','db9','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Aston Martin','DBS','aston martin','dbs','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Aston Martin','Rapide','aston martin','rapide','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Aston Martin','Vantage','aston martin','vantage','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','A1','audi','a1','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','A3','audi','a3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','A4','audi','a4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','A5','audi','a5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','A6','audi','a6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','A7','audi','a7','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','A8','audi','a8','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','Q2','audi','q2','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','Q3','audi','q3','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','Q5','audi','q5','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','Q7','audi','q7','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','Q8','audi','q8','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','R8','audi','r8','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','RS3','audi','rs3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','RS4','audi','rs4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','RS5','audi','rs5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','RS6','audi','rs6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','RS7','audi','rs7','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','S3','audi','s3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','S4','audi','s4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','S5','audi','s5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','S6','audi','s6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','S7','audi','s7','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','S8','audi','s8','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Audi','TT','audi','tt','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','116i','bmw','116i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','118i','bmw','118i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','120i','bmw','120i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','125i','bmw','125i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','128i','bmw','128i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','130i','bmw','130i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','218i','bmw','218i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','220i','bmw','220i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','228i','bmw','228i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','230i','bmw','230i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','316i','bmw','316i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','318i','bmw','318i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','320i','bmw','320i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','325i','bmw','325i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','328i','bmw','328i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','330i','bmw','330i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','335i','bmw','335i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','340i','bmw','340i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','418i','bmw','418i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','420i','bmw','420i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','428i','bmw','428i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','430i','bmw','430i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','435i','bmw','435i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','440i','bmw','440i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','520i','bmw','520i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','523i','bmw','523i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','525i','bmw','525i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','528i','bmw','528i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','530i','bmw','530i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','535i','bmw','535i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','540i','bmw','540i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','545i','bmw','545i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','550i','bmw','550i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','630i','bmw','630i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','640i','bmw','640i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','650i','bmw','650i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','730i','bmw','730i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','740i','bmw','740i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','750i','bmw','750i','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','M2','bmw','m2','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','M3','bmw','m3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','M4','bmw','m4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','M5','bmw','m5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','M6','bmw','m6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','X1','bmw','x1','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','X2','bmw','x2','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','X3','bmw','x3','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','X4','bmw','x4','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','X5','bmw','x5','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','X6','bmw','x6','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','X7','bmw','x7','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','Z4','bmw','z4','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BYD','Atto 3','byd','atto 3','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BYD','Dolphin','byd','dolphin','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BYD','EA1','byd','ea1','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BYD','Han','byd','han','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BYD','Seal','byd','seal','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BYD','Song Plus','byd','song plus','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BYD','Tang','byd','tang','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chery','Arrizo 5','chery','arrizo 5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chery','Arrizo 6','chery','arrizo 6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chery','Tiggo 2','chery','tiggo 2','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chery','Tiggo 3','chery','tiggo 3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chery','Tiggo 4','chery','tiggo 4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chery','Tiggo 5','chery','tiggo 5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chery','Tiggo 7','chery','tiggo 7','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chery','Tiggo 8','chery','tiggo 8','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Agile','chevrolet','agile','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Astra','chevrolet','astra','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Aveo','chevrolet','aveo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Blazer','chevrolet','blazer','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Camaro','chevrolet','camaro','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Captiva','chevrolet','captiva','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Cavalier','chevrolet','cavalier','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Classic','chevrolet','classic','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Cobalt','chevrolet','cobalt','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Colorado','chevrolet','colorado','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Corsa','chevrolet','corsa','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Corvette','chevrolet','corvette','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Cruze','chevrolet','cruze','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Equinox','chevrolet','equinox','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Express','chevrolet','express','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','HHR','chevrolet','hhr','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Joy','chevrolet','joy','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Meriva','chevrolet','meriva','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Malibu','chevrolet','malibu','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Montana','chevrolet','montana','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Onix','chevrolet','onix','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Onix Plus','chevrolet','onix plus','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Orlando','chevrolet','orlando','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Prisma','chevrolet','prisma','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','S10','chevrolet','s10','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Sail','chevrolet','sail','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Silverado','chevrolet','silverado','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Sonic','chevrolet','sonic','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Spark','chevrolet','spark','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Spin','chevrolet','spin','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Suburban','chevrolet','suburban','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Tahoe','chevrolet','tahoe','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Tornado','chevrolet','tornado','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Tracker','chevrolet','tracker','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Trail Blazer','chevrolet','trail blazer','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Traverse','chevrolet','traverse','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Vectra','chevrolet','vectra','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chevrolet','Zafira','chevrolet','zafira','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','200','chrysler','200','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','300','chrysler','300','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','300C','chrysler','300c','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','Crossfire','chrysler','crossfire','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','Neon','chrysler','neon','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','Pacifica','chrysler','pacifica','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','PT Cruiser','chrysler','pt cruiser','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','Sebring','chrysler','sebring','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','Town & Country','chrysler','town country','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Chrysler','Voyager','chrysler','voyager','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','Aircross','citroen','aircross','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','Berlingo','citroen','berlingo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C3','citroen','c3','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C3 Aircross','citroen','c3 aircross','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C4','citroen','c4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C4 Cactus','citroen','c4 cactus','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C4 Lounge','citroen','c4 lounge','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C4 Picasso','citroen','c4 picasso','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C-Elysee','citroen','c elysee','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C5','citroen','c5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C5 Aircross','citroen','c5 aircross','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C6','citroen','c6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','C8','citroen','c8','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','DS3','citroen','ds3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','DS4','citroen','ds4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','DS5','citroen','ds5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','Jumper','citroen','jumper','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','Jumpy','citroen','jumpy','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','Xsara','citroen','xsara','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Citroen','Xsara Picasso','citroen','xsara picasso','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daewoo','Cielo','daewoo','cielo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daewoo','Espero','daewoo','espero','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daewoo','Lanos','daewoo','lanos','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daewoo','Leganza','daewoo','leganza','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daewoo','Matiz','daewoo','matiz','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daewoo','Nubira','daewoo','nubira','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daewoo','Tacuma','daewoo','tacuma','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daihatsu','Boon','daihatsu','boon','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daihatsu','Charade','daihatsu','charade','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daihatsu','Cuore','daihatsu','cuore','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daihatsu','Feroza','daihatsu','feroza','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daihatsu','Sirion','daihatsu','sirion','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daihatsu','Terios','daihatsu','terios','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Daihatsu','YRV','daihatsu','yrv','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Avenger','dodge','avenger','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Caliber','dodge','caliber','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Challenger','dodge','challenger','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Charger','dodge','charger','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Dakota','dodge','dakota','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Dart','dodge','dart','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Durango','dodge','durango','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Journey','dodge','journey','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Neon','dodge','neon','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Ram','dodge','ram','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Dodge','Viper','dodge','viper','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('DS','DS3','ds','ds3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('DS','DS4','ds','ds4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('DS','DS5','ds','ds5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('DS','DS7','ds','ds7','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','296','ferrari','296','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','458','ferrari','458','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','488','ferrari','488','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','California','ferrari','california','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','F430','ferrari','f430','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','F8','ferrari','f8','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','GTC4Lusso','ferrari','gtc4lusso','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','Portofino','ferrari','portofino','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','Roma','ferrari','roma','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ferrari','SF90','ferrari','sf90','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','500','fiat','500','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','500X','fiat','500x','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','600','fiat','600','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Argo','fiat','argo','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Bravo','fiat','bravo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Cronos','fiat','cronos','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Doblo','fiat','doblo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Ducato','fiat','ducato','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Fastback','fiat','fastback','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Fiorino','fiat','fiorino','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Grand Siena','fiat','grand siena','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Idea','fiat','idea','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Linea','fiat','linea','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Marea','fiat','marea','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Mobi','fiat','mobi','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Pulse Abarth','fiat','pulse abarth','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Palio','fiat','palio','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Palio Weekend','fiat','palio weekend','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Panda','fiat','panda','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Pulse','fiat','pulse','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Punto','fiat','punto','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Qubo','fiat','qubo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Siena','fiat','siena','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Strada','fiat','strada','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Tipo','fiat','tipo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Toro','fiat','toro','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Fiat','Uno','fiat','uno','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Courier','ford','courier','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Bronco','ford','bronco','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','EcoSport','ford','ecosport','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Edge','ford','edge','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Escape','ford','escape','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Expedition','ford','expedition','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Explorer','ford','explorer','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','F-150','ford','f 150','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','F-250','ford','f 250','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','F-350','ford','f 350','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Fiesta','ford','fiesta','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Focus','ford','focus','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Fusion','ford','fusion','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Galaxy','ford','galaxy','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Ka','ford','ka','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Kuga','ford','kuga','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Maverick','ford','maverick','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Mondeo','ford','mondeo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Mustang','ford','mustang','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Puma','ford','puma','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Ranger','ford','ranger','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','S-MAX','ford','s max','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Territory','ford','territory','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Thunderbird','ford','thunderbird','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ford','Transit','ford','transit','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('GAC','Empow','gac','empow','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('GAC','GS3','gac','gs3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('GAC','GS4','gac','gs4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('GAC','GS8','gac','gs8','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Genesis','G70','genesis','g70','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Genesis','G80','genesis','g80','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Genesis','G90','genesis','g90','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Genesis','GV70','genesis','gv70','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Genesis','GV80','genesis','gv80','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Great Wall','Haval H2','great wall','haval h2','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Great Wall','Haval H6','great wall','haval h6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Great Wall','Wingle 6','great wall','wingle 6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Great Wall','Wingle 7','great wall','wingle 7','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Haval','H2','haval','h2','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Haval','H6','haval','h6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Haval','H9','haval','h9','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Haval','Jolion','haval','jolion','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Accord','honda','accord','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','BR-V','honda','br v','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','City','honda','city','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Civic','honda','civic','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CR-V','honda','cr v','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CR-Z','honda','cr z','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Element','honda','element','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Fit','honda','fit','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','HR-V','honda','hr v','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Jazz','honda','jazz','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Legend','honda','legend','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Odyssey','honda','odyssey','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Pilot','honda','pilot','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Prelude','honda','prelude','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Ridgeline','honda','ridgeline','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Stream','honda','stream','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','WR-V','honda','wr v','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Accent','hyundai','accent','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Atos','hyundai','atos','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Azera','hyundai','azera','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Creta','hyundai','creta','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Elantra','hyundai','elantra','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Getz','hyundai','getz','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','H1','hyundai','h1','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','HB20','hyundai','hb20','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','i10','hyundai','i10','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','i20','hyundai','i20','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','i25','hyundai','i25','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','i30','hyundai','i30','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Ioniq','hyundai','ioniq','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Ioniq 5','hyundai','ioniq 5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Ioniq 6','hyundai','ioniq 6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','ix35','hyundai','ix35','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Kona','hyundai','kona','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Santa Fe','hyundai','santa fe','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Sonata','hyundai','sonata','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Tiburon','hyundai','tiburon','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Tucson','hyundai','tucson','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Veloster','hyundai','veloster','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hyundai','Venue','hyundai','venue','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','EX35','infiniti','ex35','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','FX35','infiniti','fx35','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','FX37','infiniti','fx37','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','G35','infiniti','g35','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','G37','infiniti','g37','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','JX35','infiniti','jx35','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','Q50','infiniti','q50','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','Q60','infiniti','q60','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','Q70','infiniti','q70','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','QX50','infiniti','qx50','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','QX56','infiniti','qx56','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','QX60','infiniti','qx60','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','QX70','infiniti','qx70','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Infiniti','QX80','infiniti','qx80','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','E-Pace','jaguar','e pace','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','F-Pace','jaguar','f pace','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','F-Type','jaguar','f type','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','I-Pace','jaguar','i pace','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','S-Type','jaguar','s type','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','X-Type','jaguar','x type','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','XE','jaguar','xe','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','XF','jaguar','xf','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','XJ','jaguar','xj','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jaguar','XK','jaguar','xk','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Avenger','jeep','avenger','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Cherokee','jeep','cherokee','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Commander','jeep','commander','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Compass','jeep','compass','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Gladiator','jeep','gladiator','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Grand Cherokee','jeep','grand cherokee','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Patriot','jeep','patriot','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Renegade','jeep','renegade','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Jeep','Wrangler','jeep','wrangler','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Carens','kia','carens','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Carnival','kia','carnival','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Ceed','kia','ceed','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Cerato','kia','cerato','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','EV6','kia','ev6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Morning','kia','morning','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Niro','kia','niro','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Optima','kia','optima','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Picanto','kia','picanto','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Rio','kia','rio','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Seltos','kia','seltos','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Sorento','kia','sorento','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Soul','kia','soul','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Sportage','kia','sportage','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Stinger','kia','stinger','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kia','Telluride','kia','telluride','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lamborghini','Aventador','lamborghini','aventador','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lamborghini','Huracan','lamborghini','huracan','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lamborghini','Urus','lamborghini','urus','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Land Rover','Defender','land rover','defender','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Land Rover','Discovery','land rover','discovery','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Land Rover','Discovery Sport','land rover','discovery sport','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Land Rover','Freelander','land rover','freelander','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Land Rover','Range Rover','land rover','range rover','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Land Rover','Range Rover Evoque','land rover','range rover evoque','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Land Rover','Range Rover Sport','land rover','range rover sport','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Land Rover','Range Rover Velar','land rover','range rover velar','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','CT200h','lexus','ct200h','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','ES','lexus','es','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','GS','lexus','gs','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','GX','lexus','gx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','IS','lexus','is','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','LC','lexus','lc','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','LS','lexus','ls','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','LX','lexus','lx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','NX','lexus','nx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','RX','lexus','rx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lexus','UX','lexus','ux','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lifan','530','lifan','530','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lifan','620','lifan','620','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lifan','720','lifan','720','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lifan','820','lifan','820','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lifan','X50','lifan','x50','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lifan','X60','lifan','x60','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lifan','X70','lifan','x70','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lincoln','Continental','lincoln','continental','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lincoln','MKC','lincoln','mkc','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lincoln','MKT','lincoln','mkt','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lincoln','MKX','lincoln','mkx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lincoln','MKZ','lincoln','mkz','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Lincoln','Navigator','lincoln','navigator','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Maserati','Ghibli','maserati','ghibli','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Maserati','GranTurismo','maserati','granturismo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Maserati','Grecale','maserati','grecale','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Maserati','Levante','maserati','levante','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Maserati','MC20','maserati','mc20','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Maserati','Quattroporte','maserati','quattroporte','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','2','mazda','2','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','3','mazda','3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','5','mazda','5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','6','mazda','6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','BT-50','mazda','bt 50','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','CX-3','mazda','cx 3','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','CX-30','mazda','cx 30','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','CX-5','mazda','cx 5','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','CX-7','mazda','cx 7','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','CX-9','mazda','cx 9','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','MX-5','mazda','mx 5','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mazda','RX-8','mazda','rx 8','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','A180','mercedes benz','a180','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','A200','mercedes benz','a200','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','A250','mercedes benz','a250','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','B200','mercedes benz','b200','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','C180','mercedes benz','c180','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','C200','mercedes benz','c200','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','C220','mercedes benz','c220','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','C250','mercedes benz','c250','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','C300','mercedes benz','c300','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','C350','mercedes benz','c350','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','C400','mercedes benz','c400','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','C450','mercedes benz','c450','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','CLA','mercedes benz','cla','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','CLK','mercedes benz','clk','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','CLS','mercedes benz','cls','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','E200','mercedes benz','e200','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','E220','mercedes benz','e220','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','E250','mercedes benz','e250','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','E300','mercedes benz','e300','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','E350','mercedes benz','e350','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','E400','mercedes benz','e400','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','E450','mercedes benz','e450','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','G350','mercedes benz','g350','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','G500','mercedes benz','g500','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','G63','mercedes benz','g63','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','GLA','mercedes benz','gla','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','GLB','mercedes benz','glb','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','GLC','mercedes benz','glc','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','GLE','mercedes benz','gle','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','GLS','mercedes benz','gls','SUV',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','ML250','mercedes benz','ml250','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','ML350','mercedes benz','ml350','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','S300','mercedes benz','s300','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','S350','mercedes benz','s350','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','S400','mercedes benz','s400','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','S450','mercedes benz','s450','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','S500','mercedes benz','s500','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','S560','mercedes benz','s560','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','S600','mercedes benz','s600','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','S63','mercedes benz','s63','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','SL','mercedes benz','sl','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','SLC','mercedes benz','slc','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','SLK','mercedes benz','slk','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','Sprinter','mercedes benz','sprinter','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','V220','mercedes benz','v220','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','V250','mercedes benz','v250','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mercedes-Benz','Vito','mercedes benz','vito','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('MG','3','mg','3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('MG','5','mg','5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('MG','6','mg','6','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('MG','HS','mg','hs','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('MG','Marvel R','mg','marvel r','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('MG','RX5','mg','rx5','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('MG','ZS','mg','zs','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mini','Cabrio','mini','cabrio','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mini','Clubman','mini','clubman','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mini','Cooper','mini','cooper','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mini','Cooper S','mini','cooper s','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mini','Countryman','mini','countryman','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mini','JCW','mini','jcw','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mini','Paceman','mini','paceman','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','ASX','mitsubishi','asx','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','Eclipse Cross','mitsubishi','eclipse cross','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','Galant','mitsubishi','galant','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','L200','mitsubishi','l200','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','Lancer','mitsubishi','lancer','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','Montero','mitsubishi','montero','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','Outlander','mitsubishi','outlander','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','Pajero','mitsubishi','pajero','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Mitsubishi','Space Star','mitsubishi','space star','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','350Z','nissan','350z','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','370Z','nissan','370z','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Altima','nissan','altima','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Armada','nissan','armada','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Frontier','nissan','frontier','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','GT-R','nissan','gt r','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Juke','nissan','juke','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Kicks','nissan','kicks','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Leaf','nissan','leaf','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','March','nissan','march','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Maxima','nissan','maxima','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Micra','nissan','micra','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Murano','nissan','murano','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Navara','nissan','navara','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','NP300','nissan','np300','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Note','nissan','note','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Pathfinder','nissan','pathfinder','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Qashqai','nissan','qashqai','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Rogue','nissan','rogue','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Sentra','nissan','sentra','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Tiida','nissan','tiida','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Titan','nissan','titan','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','Versa','nissan','versa','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Nissan','X-Trail','nissan','x trail','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','106','peugeot','106','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','107','peugeot','107','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','108','peugeot','108','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','2008','peugeot','2008','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','205','peugeot','205','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','206','peugeot','206','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','207','peugeot','207','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','208','peugeot','208','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','209','peugeot','209','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','214','peugeot','214','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','215','peugeot','215','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','301','peugeot','301','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','306','peugeot','306','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','307','peugeot','307','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','308','peugeot','308','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','3008','peugeot','3008','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','404','peugeot','404','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','405','peugeot','405','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','406','peugeot','406','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','4007','peugeot','4007','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','4008','peugeot','4008','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','408','peugeot','408','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','504','peugeot','504','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','505','peugeot','505','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','508 RXH','peugeot','508 rxh','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','5008','peugeot','5008','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','508','peugeot','508','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','607','peugeot','607','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','807','peugeot','807','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','Bipper','peugeot','bipper','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','Boxer','peugeot','boxer','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','Expert','peugeot','expert','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','Hoggar','peugeot','hoggar','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','Landtrek','peugeot','landtrek','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','Partner Patagonica','peugeot','partner patagonica','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','Partner','peugeot','partner','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','Rifter','peugeot','rifter','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Peugeot','RCZ','peugeot','rcz','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Porsche','718','porsche','718','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Porsche','911','porsche','911','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Porsche','Cayenne','porsche','cayenne','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Porsche','Macan','porsche','macan','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Porsche','Panamera','porsche','panamera','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Porsche','Taycan','porsche','taycan','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('RAM','1500','ram','1500','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('RAM','2500','ram','2500','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('RAM','3500','ram','3500','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('RAM','ProMaster','ram','promaster','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('RAM','Rampage','ram','rampage','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Alaskan','renault','alaskan','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Captur','renault','captur','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Clio','renault','clio','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Express','renault','express','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Duster','renault','duster','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Fluence','renault','fluence','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Kardian','renault','kardian','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Kangoo','renault','kangoo','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Koleos','renault','koleos','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Kwid','renault','kwid','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Laguna','renault','laguna','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Latitude','renault','latitude','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Logan','renault','logan','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Master','renault','master','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Megane','renault','megane','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Oroch','renault','oroch','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Sandero','renault','sandero','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Scenic','renault','scenic','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Stepway','renault','stepway','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Symbol','renault','symbol','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Trafic','renault','trafic','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Twingo','renault','twingo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Renault','Zoe','renault','zoe','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('SEAT','Arona','seat','arona','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('SEAT','Ateca','seat','ateca','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('SEAT','Cordoba','seat','cordoba','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('SEAT','Ibiza','seat','ibiza','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('SEAT','Leon','seat','leon','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('SEAT','Toledo','seat','toledo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Skoda','Fabia','skoda','fabia','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Skoda','Karoq','skoda','karoq','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Skoda','Kodiaq','skoda','kodiaq','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Skoda','Octavia','skoda','octavia','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Skoda','Rapid','skoda','rapid','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Skoda','Superb','skoda','superb','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Skoda','Yeti','skoda','yeti','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Smart','Forfour','smart','forfour','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Smart','Fortwo','smart','fortwo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Subaru','Forester','subaru','forester','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Subaru','Impreza','subaru','impreza','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Subaru','Legacy','subaru','legacy','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Subaru','Outback','subaru','outback','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Subaru','Tribeca','subaru','tribeca','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Subaru','WRX','subaru','wrx','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Subaru','XV','subaru','xv','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Baleno','suzuki','baleno','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Celerio','suzuki','celerio','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Ertiga','suzuki','ertiga','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Grand Vitara','suzuki','grand vitara','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Ignis','suzuki','ignis','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Jimny','suzuki','jimny','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Kizashi','suzuki','kizashi','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','S-Cross','suzuki','s cross','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Swift','suzuki','swift','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Vitara','suzuki','vitara','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','SX4','suzuki','sx4','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Tesla','Model 3','tesla','model 3','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Tesla','Model S','tesla','model s','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Tesla','Model X','tesla','model x','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Tesla','Model Y','tesla','model y','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','4Runner','toyota','4runner','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Avalon','toyota','avalon','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','C-HR','toyota','c hr','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Camry','toyota','camry','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Corolla','toyota','corolla','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Corolla Cross','toyota','corolla cross','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Etios','toyota','etios','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','FJ Cruiser','toyota','fj cruiser','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Fortuner','toyota','fortuner','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','GR86','toyota','gr86','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Hiace','toyota','hiace','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Highlander','toyota','highlander','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Hilux','toyota','hilux','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Innova','toyota','innova','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Land Cruiser','toyota','land cruiser','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Land Cruiser Prado','toyota','land cruiser prado','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Prius','toyota','prius','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','RAV4','toyota','rav4','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Rush','toyota','rush','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Sequoia','toyota','sequoia','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Sienna','toyota','sienna','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','SW4','toyota','sw4','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Tacoma','toyota','tacoma','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Tundra','toyota','tundra','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Vios','toyota','vios','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Toyota','Yaris','toyota','yaris','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Amarok','volkswagen','amarok','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Bora','volkswagen','bora','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Caddy','volkswagen','caddy','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Caravelle','volkswagen','caravelle','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Crafter','volkswagen','crafter','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Fox','volkswagen','fox','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Gol','volkswagen','gol','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Gol Trend','volkswagen','gol trend','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Golf','volkswagen','golf','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Golf GTI','volkswagen','golf gti','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Golf R','volkswagen','golf r','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Jetta','volkswagen','jetta','Coupe',0.8800,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Nivus','volkswagen','nivus','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Passat','volkswagen','passat','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Polo','volkswagen','polo','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Polo Track','volkswagen','polo track','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Saveiro','volkswagen','saveiro','Camioneta',0.9500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Sharan','volkswagen','sharan','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Suran','volkswagen','suran','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','T-Cross','volkswagen','t cross','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','T-Roc','volkswagen','t roc','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Taos','volkswagen','taos','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Tiguan','volkswagen','tiguan','SUV',0.9200,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Touareg','volkswagen','touareg','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Touran','volkswagen','touran','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Transporter','volkswagen','transporter','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','up!','volkswagen','up','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Vento','volkswagen','vento','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Virtus','volkswagen','virtus','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volkswagen','Vivo','volkswagen','vivo','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','C30','volvo','c30','Hatchback',0.9000,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','S40','volvo','s40','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','S60','volvo','s60','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','S80','volvo','s80','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','S90','volvo','s90','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','V40','volvo','v40','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','V50','volvo','v50','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','V60','volvo','v60','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','V70','volvo','v70','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','V90','volvo','v90','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','XC40','volvo','xc40','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','XC60','volvo','xc60','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','XC70','volvo','xc70','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Volvo','XC90','volvo','xc90','Sedan',0.5500,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Avenger 160','bajaj','avenger 160','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Avenger 220','bajaj','avenger 220','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Boxer 150','bajaj','boxer 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','CT 100','bajaj','ct 100','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Discover 125','bajaj','discover 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Dominar 250','bajaj','dominar 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Dominar 400','bajaj','dominar 400','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','NS 125','bajaj','ns 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','NS 160','bajaj','ns 160','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','NS 200','bajaj','ns 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Platina 100','bajaj','platina 100','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Platina 110','bajaj','platina 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Pulsar 125','bajaj','pulsar 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Pulsar 150','bajaj','pulsar 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Pulsar 160','bajaj','pulsar 160','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Pulsar 180','bajaj','pulsar 180','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Pulsar 200','bajaj','pulsar 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Pulsar 220','bajaj','pulsar 220','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Pulsar NS 200','bajaj','pulsar ns 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Pulsar RS 200','bajaj','pulsar rs 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Rouser 135','bajaj','rouser 135','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Rouser 180','bajaj','rouser 180','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Rouser 200','bajaj','rouser 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Bajaj','Rouser 220','bajaj','rouser 220','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Benelli','302R','benelli','302r','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Benelli','502C','benelli','502c','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Benelli','600i','benelli','600i','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Benelli','752S','benelli','752s','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Benelli','Leoncino 500','benelli','leoncino 500','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Benelli','TRK 502','benelli','trk 502','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Benelli','TRK 800','benelli','trk 800','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','BS 110','beta','bs 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','BS 150','beta','bs 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','City 110','beta','city 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','Motard 200','beta','motard 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','Motard 250','beta','motard 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','RR 200','beta','rr 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','RR 250','beta','rr 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','RR 300','beta','rr 300','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','Tempo 125','beta','tempo 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','Tempo 150','beta','tempo 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','Urban 150','beta','urban 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','Urban 200','beta','urban 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Beta','Urban 250','beta','urban 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','F700GS','bmw','f700gs','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','F750GS','bmw','f750gs','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','F800GS','bmw','f800gs','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','F850GS','bmw','f850gs','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','G310GS','bmw','g310gs','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','G310R','bmw','g310r','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','K1200GT','bmw','k1200gt','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','K1300GT','bmw','k1300gt','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','R1200GS','bmw','r1200gs','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','R1250GS','bmw','r1250gs','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','S1000R','bmw','s1000r','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','S1000RR','bmw','s1000rr','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('BMW','S1000XR','bmw','s1000xr','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Bamx 110','corven','bamx 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Energy 110','corven','energy 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Energy 125','corven','energy 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Mirage 110','corven','mirage 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Road 110','corven','road 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Terrain 250','corven','terrain 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Triax 150','corven','triax 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Triax 200','corven','triax 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Corven','Triax 250','corven','triax 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ducati','Diavel','ducati','diavel','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ducati','Hypermotard','ducati','hypermotard','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ducati','Monster','ducati','monster','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ducati','Multistrada','ducati','multistrada','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ducati','Panigale','ducati','panigale','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ducati','Scrambler','ducati','scrambler','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Ducati','SuperSport','ducati','supersport','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Gilera','RK6 200','gilera','rk6 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Gilera','Smash 110','gilera','smash 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Gilera','Smash V6','gilera','smash v6','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Breakout','harley davidson','breakout','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Fat Bob','harley davidson','fat bob','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Fat Boy','harley davidson','fat boy','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','FLHR','harley davidson','flhr','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','FLSTC','harley davidson','flstc','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Heritage Softail','harley davidson','heritage softail','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Iron 883','harley davidson','iron 883','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Low Rider','harley davidson','low rider','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Night Rod','harley davidson','night rod','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Road King','harley davidson','road king','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Softail','harley davidson','softail','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Sportster','harley davidson','sportster','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Street 500','harley davidson','street 500','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Street Glide','harley davidson','street glide','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Street Rod','harley davidson','street rod','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Harley-Davidson','Ultra Classic','harley davidson','ultra classic','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hero','Dash 110','hero','dash 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hero','Eco Deluxe 100','hero','eco deluxe 100','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hero','Hunk 150','hero','hunk 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hero','Ignitor 125','hero','ignitor 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hero','Passion Pro 110','hero','passion pro 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Hero','Splendor','hero','splendor','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 125','honda','cb 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 190','honda','cb 190','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 250 Twister','honda','cb 250 twister','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 300R','honda','cb 300r','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 500F','honda','cb 500f','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 500X','honda','cb 500x','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 600F Hornet','honda','cb 600f hornet','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 750','honda','cb 750','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CB 1000R','honda','cb 1000r','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CBR 300R','honda','cbr 300r','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CBR 600RR','honda','cbr 600rr','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CBR 1000RR','honda','cbr 1000rr','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CG 150','honda','cg 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CRF 250','honda','crf 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','CRF 450','honda','crf 450','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Elite 125','honda','elite 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','NC 700X','honda','nc 700x','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','NC 750X','honda','nc 750x','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','NXR 150','honda','nxr 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','PCX 150','honda','pcx 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Pop 100','honda','pop 100','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Tornado 250','honda','tornado 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','VT 750','honda','vt 750','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','Wave 110','honda','wave 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','XR 250','honda','xr 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Honda','XRE 300','honda','xre 300','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Indian','Chief','indian','chief','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Indian','Chieftain','indian','chieftain','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Indian','Scout','indian','scout','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Indian','Scout Bobber','indian','scout bobber','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Indian','Springfield','indian','springfield','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Indian','Vintage','indian','vintage','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Ninja 300','kawasaki','ninja 300','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Ninja 400','kawasaki','ninja 400','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Ninja 650','kawasaki','ninja 650','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Ninja ZX-6R','kawasaki','ninja zx 6r','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Ninja ZX-10R','kawasaki','ninja zx 10r','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Ninja H2','kawasaki','ninja h2','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','KX450F','kawasaki','kx450f','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Versys 300','kawasaki','versys 300','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Versys 650','kawasaki','versys 650','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Versys 1000','kawasaki','versys 1000','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Vulcan S','kawasaki','vulcan s','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Z400','kawasaki','z400','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Z650','kawasaki','z650','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Z900','kawasaki','z900','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kawasaki','Z1000','kawasaki','z1000','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','200 Duke','ktm','200 duke','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','250 Duke','ktm','250 duke','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','390 Duke','ktm','390 duke','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','690 Duke','ktm','690 duke','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','790 Duke','ktm','790 duke','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','890 Duke','ktm','890 duke','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','200 EXC','ktm','200 exc','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','250 EXC','ktm','250 exc','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','300 EXC','ktm','300 exc','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','450 EXC','ktm','450 exc','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','500 EXC','ktm','500 exc','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','RC 200','ktm','rc 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','RC 390','ktm','rc 390','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','1090 Adventure','ktm','1090 adventure','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','1190 Adventure','ktm','1190 adventure','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('KTM','1290 Super Duke','ktm','1290 super duke','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kymco','AK 550','kymco','ak 550','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kymco','Downtown 125','kymco','downtown 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kymco','Downtown 350','kymco','downtown 350','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kymco','Like 125','kymco','like 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kymco','Spade 150','kymco','spade 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Kymco','Xciting S 400','kymco','xciting s 400','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','Blitz 110','motomel','blitz 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','CG 150','motomel','cg 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','CG 200','motomel','cg 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','Cub 110','motomel','cub 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','Custom 150','motomel','custom 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','Custom 200','motomel','custom 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','Go 50','motomel','go 50','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','S2 110','motomel','s2 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','S3 150','motomel','s3 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','Sirius 150','motomel','sirius 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','Strato 125','motomel','strato 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','Strato 150','motomel','strato 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','X3M 200','motomel','x3m 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Motomel','X3M 250','motomel','x3m 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Address 110','suzuki','address 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','AN 125','suzuki','an 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','AN 400','suzuki','an 400','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Burgman 125','suzuki','burgman 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Burgman 400','suzuki','burgman 400','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','DL 1000','suzuki','dl 1000','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','DR 160','suzuki','dr 160','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','DR 200','suzuki','dr 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','DR 650','suzuki','dr 650','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','GS500','suzuki','gs500','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','GSR 150','suzuki','gsr 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','GSX-R600','suzuki','gsx r600','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','GSX-R750','suzuki','gsx r750','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','GSX-R1000','suzuki','gsx r1000','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','GSX-S750','suzuki','gsx s750','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','GSX-S1000','suzuki','gsx s1000','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Hayabusa','suzuki','hayabusa','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','Inazuma 250','suzuki','inazuma 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','V-Strom 650','suzuki','v strom 650','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Suzuki','V-Strom 1000','suzuki','v strom 1000','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Triumph','Bonneville','triumph','bonneville','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Triumph','Daytona 675','triumph','daytona 675','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Triumph','Rocket III','triumph','rocket iii','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Triumph','Speed Triple','triumph','speed triple','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Triumph','Street Triple','triumph','street triple','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Triumph','Thruxton','triumph','thruxton','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Triumph','Tiger','triumph','tiger','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Triumph','Tiger Sport','triumph','tiger sport','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Vespa','GTS 125','vespa','gts 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Vespa','GTS 250','vespa','gts 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Vespa','GTS 300','vespa','gts 300','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Vespa','LX 125','vespa','lx 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Vespa','LX 150','vespa','lx 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Vespa','Primavera 125','vespa','primavera 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Vespa','Sprint 125','vespa','sprint 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Vespa','Sprint 150','vespa','sprint 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','Biz 125','yamaha','biz 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','Crypton 115','yamaha','crypton 115','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','DT 175','yamaha','dt 175','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','DT 200','yamaha','dt 200','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','FZ 15','yamaha','fz 15','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','FZ 16','yamaha','fz 16','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','FZ 25','yamaha','fz 25','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','FZ-S','yamaha','fz s','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','FZN 150','yamaha','fzn 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','MT-03','yamaha','mt 03','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','MT-07','yamaha','mt 07','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','MT-09','yamaha','mt 09','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','MT-10','yamaha','mt 10','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','R1','yamaha','r1','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','R3','yamaha','r3','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','R6','yamaha','r6','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','R15','yamaha','r15','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','SR 150','yamaha','sr 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','T-Max 530','yamaha','t max 530','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','TDM 900','yamaha','tdm 900','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','TFX 150','yamaha','tfx 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','Tenere 250','yamaha','tenere 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','Tenere 700','yamaha','tenere 700','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','V-Max','yamaha','v max','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','XJ6','yamaha','xj6','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','XTZ 125','yamaha','xtz 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','XTZ 150','yamaha','xtz 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','XTZ 250','yamaha','xtz 250','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','XTZ 660','yamaha','xtz 660','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','XT 660','yamaha','xt 660','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','YBR 125','yamaha','ybr 125','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','YCZ 110','yamaha','ycz 110','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW()),
('Yamaha','YS 150','yamaha','ys 150','Moto',0.9900,1,'local_seed_bulk',NULL,NOW(),NOW())
ON CONFLICT (normalized_brand, normalized_model)
DO UPDATE SET
  body_type = EXCLUDED.body_type,
  confidence = EXCLUDED.confidence,
  sample_size = EXCLUDED.sample_size,
  source = EXCLUDED.source,
  updated_at = NOW();

COMMIT;
